import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';
import Footer from './footer';
import Main from './main';
import Navbar from './navbar';
import SearchField from './searchField';

export default function Home() {
	// for dark mode
	const [dark, setDark] = useState(false);
	const darkMode = () => {
		setDark(!dark);
		console.log(dark);
	};
	// for dark mode End

	return (
		<div className={styles.container}>
			<div className={dark ? ' bg-black' : 'bg-white'}>
				<Head>
					<title>Create Next App</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>

				<Navbar darkMode={darkMode} dark={dark}></Navbar>

				<SearchField dark={dark}></SearchField>
				<Main dark={dark}></Main>
				<Footer dark={dark}></Footer>
			</div>
		</div>
	);
}
